### ISSUE TITLE
Just use pytorch ==0.2.0 ???

### ISSUE THREAD

**Issue by Zhen-ao** [divyam02/dafrcnn-pytorch#3]
I use pytorch==0.4.0,python=3.6, 
where sh make.sh, I find the error: 
ModuleNotFoundError: No module named 'model.nms._ext.nms._nms'

please tell me

**Comment by ZongxianLee** [comment]
I also met the problem when I sh make.sh, something is lost in this code, you would better copy some source code from https://github.com/jwyang/faster-rcnn.pytorch

**Comment by ZongxianLee** [comment]
pytorch == 0.4.0 is ok!

**Comment by ZongxianLee** [comment]
Sooooo many intend problem is this project!!!! Spent nearly 2 days for finding and solving lots of mysterious problems caused by wrong intends!!!!!!

**Comment by divyam02** [comment]
Noted. Will resolve this in the cleaning branch of the repository.

**Comment by ZongxianLee** [comment]
> Noted. Will resolve this in the cleaning branch of the repository.

Anyway, thank you very much for your code！The code clearly explains the paper！
