### ISSUE TITLE
Only single batch implemented? 

### ISSUE THREAD

**Issue by ZongxianLee** [divyam02/dafrcnn-pytorch#4]
I found you mentioned that "only single image batch implemented", but when i set the batch size bigger than 1(specifically fixed at 8), the code runs well, but the total loss is extremely small(closes to 0.01 after only 100 iters ), while the faster rcnn loss seems quite normal?  
Does the  comment "only single image batch implemented" mean that the batch size should be fixed at 1? Or the source batchsize can be relatively large？

**Comment by divyam02** [comment]
It means that the domain classifier is updating weights after processing a single source and target image. You may check the paper on which this implementation is based, they used a single image per batch as well.

**Comment by ZongxianLee** [comment]
> It means that the domain classifier is updating weights after processing a single source and target image. You may check the paper on which this implementation is based, they used a single image per batch as well.

Ok, it works well after fixing the indent problem....hhhh
